### PR TITLE
Refactoring of tests

### PR DESCRIPTION
**Pull request by 2xyo**
- Use  of `unittest` module 
  - Run tests with command `$ python -m unittest discover` or `$ python tests/test_olefile.py`
- Remove  unused code
- Add support for continuous test [Travis-Ci](https://travis-ci.org/2xyo/olefile)

### CODE REVIEW

**Comment by hugovk** [comment]
@2xyo There's a merge conflict in .travis.yml

**Comment by 2xyo** [comment]
@hugovk because of decalage2/olefile#36 

Let me fix that this week.

**Comment by 2xyo** [comment]
@hugovk master branch synced and merge conflict fixed :smile: 

I also update  `$ python -m unittest discover ` to `$ python -m unittest tests` for 2.6 compatibility (who use 2.6 !?)

**Comment by decalage2** [comment]
Python 2.6 compatibility is still useful for machines running RHEL or CentOS 6.x, for example. It is not always possible to upgrade to Python 2.7.

**Pull request merged**
