### PR TITLE
Move non-library package data outside of package by using MANIFEST.in

### PR DESCRIPTION
**Pull request by jdufresne**
To add additional files to the package distribution can use `MANIFEST.in`. This avoids having the files themselves installed as Python files used by the package. As these files are not used by the actual Python code, no need to install alongside the library.

Merges the multiple `README` files into one.

### CODE REVIEW

**Comment by hugovk** [comment]
I personally vote for Markdown rather than reStructuredText as the top-level README, I find it easier to use and it's the default format elsewhere on GitHub (like for these PRs/issues).

**Comment by jdufresne** [comment]
> I personally vote for Markdown rather than reStructuredText as the top-level README, I find it easier to use and it's the default format elsewhere on GitHub (like for these PRs/issues).

I'm fine with either format, but I specifically chose reStructuredText as that is the only format supported by PyPI. With that in mind would you still like me to switch to the Markdown format?

**Comment by decalage2** [comment]
Well, actually I use this structure on purpose: I want the package to be distributed and installed with its license and readme files. Even if python does not use those files, they need to stay with the code. This is to make sure the readme and license are kept even if someone copies the folder somewhere else, or uses it to create a package of some sort.

Also, I already have a MANIFEST.in file locally, that I use to build the package for PyPI. 

And finally, my master readme file is olefile/README.md. I use pandoc to generate the .rst version for PyPI automatically before packaging.

So overall, I prefer not to accept this PR. We can of course discuss this further, if you think there are real issues due to the project structure I use.

**Comment by jdufresne** [comment]
> I want the package to be distributed and installed with its license

This is supported directly by Python packaging. To do this, add a `[metadata]` section to `setup.cfg` with `license-file`. Then the license file with be installed int the package's `dist-info` directory. I have done this in the latest revision. If you reopen the PR, you'll see. (See information in [wheel package](https://bitbucket.org/pypa/wheel/issues/47/include-full-license-text-in-dist-info).)

> ... installed ... readme files.

Why? This is quite unusual. I'm not familiar with any other Python package installing their README alongside the source, including Pillow. Normally Python packages include the README in the distribution (which is still happening with my PR) but not in the installed directory. Do you have additional reasons for doing this? Further, the documentation should be available online for easy viewing.

> Also, I already have a MANIFEST.in file locally, that I use to build the package for PyPI.

Thanks! I've rebased on your change in the latest revision. If you reopen the PR, you'll see.

> And finally, my master readme file is /README.md (for GitHub).

Fixed. I've restored the `md` file and move the `rst` & `html` file to the top level for PyPI. 

>  I use pandoc to generate the olefile/README.rst version for PyPI automatically before packaging, and also olefile/README.html.

You may wish to include this as an automatic step in the future, so it could be available for all developers. I'm happy to open a PR if you're interested.

> So overall, I prefer not to accept this PR. We can of course discuss this further, if you think there are real issues due to the project structure I use.

One of the reasons I opened this, olefile is basically a package with 1 file, `__init__.py` (after you forget about the compatibility workarounds). Packages that are 1 file should normally be a module instead. For example, change `olefile/__init__.py` -> `olefile.py`.

By removing the unconventional package data, I was hoping this would be a step towards that goal of fixing olefile from a one file package to a module.

If this were accepted, my plan was to follow up with the structural fix.

**Comment by decalage2** [comment]
Well, olefile used to be a single module a few years ago. I changed it to a package in order to include the license and readme files ;-). I find it cleaner to have separate directories for each package, rather than a lot of modules in the same dir, without any readme or license. This is just to avoid people copying the code for their own projects, without including the license. But maybe you're right, I'll have another look at your PR. (It seems I can't reopen it as-is from Github, though)

**Comment by jdufresne** [comment]
> I'll have another look at your PR

Thanks. I've reopened it as PR #72.

**Pull request closed without merging**
